### ISSUE TITLE
Unstable builds

### ISSUE THREAD

**Issue by eilrix** [ONLYOFFICE/build_tools#378]
**Describe your problem**:

After running [build from sources via automate.py](https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx) I get multiple errors in applications.

At first web app crashed because it could not load `dkjs/common/AllFonts.js` (404 error, probably because it wasn't built, but script https://github.com/ONLYOFFICE/build_tools#generate-fonts-data runs fine, no ouput and no errors.

After I copied sdkjs directory from [distributuon build](https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx), Web app at `web-apps/apps/documenteditor/main/app.js` started to throw error: `TypeError: _user.put_IsAnonymousUser is not a function`. That's an error in JS file wich can be solved by commenting out the line in code that causes it.

Then I started to have problems with the server. Document server cannot process requests in form: `doc/1111277013/c/210/01jlzhz4/xhr?t=1630947606435`. They're pending for a while until connection timeout. Though the server started without errors and some other requests are processed fine. There are no errors in server logs. 
Frontend simply displays loading screen, no errors in console.

My guess is that since the automated build is targeted at master branches and these branches are frequently updated, it produces unstable untested builds that are very likely to fail. I don't blame that development branches can fail in production build (and it is quite expected), but it makes sense to target build script at stable and tested release branches.

Since I couldn't find any release branches, could you tell me please what stable [commit or branch in the server repo](https://github.com/ONLYOFFICE/server) I can take to make the build work?

**Steps to reproduce the problem**:
Follow instructions at https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx

**Operating system**: Ubuntu 14.04

**Comment by ShockwaveNN** [comment]
I recently rechecked build instruction and didn't find any problem you mention but I'll try to responce you point by point

> it could not load sdkjs/common/AllFonts.js

I think this may be problem with nginx configuration, never seen error like this

> Web app at web-apps/apps/documenteditor/main/app.js started to throw error: TypeError: _user.put_IsAnonymousUser is not a function

I think this maybe because version mismatch - possible you build your source code from v6.3.1 and place web-apps from v6.4.0. Please note that we release v6.4.0 several days ago

> Document server cannot process requests in form: doc/1111277013/c/210/01jlzhz4/xhr?t=1630947606435.

I think once again - this is nginx configuration problem, maybe there is some errors in nginx logs why it happened

> automated build is targeted at master branches and these branches are frequently updated

No it's not, master brancher are rarely updated, only then we do a release - it's about once in 2-3 months in general

> could you tell me please what stable commit or branch in the server repo I can take to make the build work?

You algorithm of building should be:

1. Fetch latest master version of `build_tools` (never forget to `git pull` this repo, sometimes people create an issue in which build_tools were very old
2. Run build script and it download all master branches of all required repos itself
3. If something wrong - better to create issue about this, because replacing one problematic source file with file with distributed build - can cause a lot more trouble and make it harder to identify problem.

**Comment by eilrix** [comment]
Thanks, after `git pull`, full cleanup and rebuild it launched without errors. 
Though SpellChecker service wasn't built. SpellChecker directory is absent in `out/linux_64/onlyoffice/documentserver/server`. I don't see any related build errors.
Active Node.js v10.14.0 as installed by the build script.

**Comment by ShockwaveNN** [comment]
> Though SpellChecker service wasn't built

Spellchecker service now is not separate service, we just do not removed it by planning to do it

Spellcheck should work on your instance without separate service

**Comment by eilrix** [comment]
Yeah, spellchecking actually works in the editor. Thanks!
