### ISSUE TITLE
automate.py install packages  and other stuff 

### ISSUE THREAD

**Issue by hahaxd35** [ONLYOFFICE/build_tools#399]
**Describe your problem**:
automate.py should only configure the software i think.... 
as far as i used compiling others software: it allways abouted my compiling because of missing packages 

is this normal there days? (automate.py like "sudo apt install -y package" ) 

i have no plan how to remove all this package again after not needing this software anymore.... 
and you add third party repository to the system that might have in the future security issues. like NPM has right now

i thinks this  is not the best practice

**Comment by ShockwaveNN** [comment]
It's a way our dev team designed it, I know that's not usual way to compiling software, but it's the way it is

And if you don't want to remove package after that - you better use Dockerfile in this repo, I'm using it myself regularly, without need to install or remove additional software

**Comment by hahaxd35** [comment]
okay no problem, but maybe it just asking? i

wildcard and autoremove should remove the most. 


i only want to compile, nothing else. Docker is not our best frend ;-)

**Comment by ShockwaveNN** [comment]
> Docker is not our best frend

But Docker is our best friend and personally, I see not a single reason not to use it

> wildcard and autoremove should remove the most.

I'm not sure that our developers have time to refactor this piece of code, but feel free to make PR 

If you telling about this line of code
https://github.com/ONLYOFFICE/build_tools/blob/8381ef6c24b6af1d058281de9ffe146005571e99/tools/linux/automate.py#L72

It's mostly because if nodejs is very old - the build process will fail with the usage of old nodejs
I understand that removing the installed version is a little bit harsh, but it works well in our build process and I'm not sure that is an alternative - just failing and stopping building or showing confirmation (and adding parameters to ignore this confirmation for automated build)

So a lot of questions I cannot answer )

**Comment by hahaxd35** [comment]
if nodejs -v <= 9 
echo "please update jour nodeJS to version 11"
exit ;-) 

making PR was my next step :)

**Comment by ShockwaveNN** [comment]
Yes it's a simplest solution, but we want that our scripts do all installation by itself and no human interaction is needed
