### ISSUE TITLE
missing files in the tools submodule - src

### ISSUE THREAD

**Issue by bhlevca** [ONLYOFFICE/build_tools#461]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux (DEB package)

### Version information

sourc latest

### Expected Behavior

when `bootstrap.sh` is called by various scripts including `make.py `  calls nonexistent  files in nonexistent directory [src](url)
`./bootstrap.sh: 1: ./tools/build/src/engine/build.sh: not found`

### Actual Behavior

checkout from the repository on a clean directory and try to compile. It will fail.

### Reproduction Steps

checkout from the repository on a clean directory and try to compile. It will fail.

**Comment by bhlevca** [comment]
> Hi, are you sure you've using latest version of `build_tools`
> 
> Could you point out which exact revision from gith you've cloned?
> 
> I don't think that we have a script named `tools/build/src/engine/build.sh` in our current master branches or point out the exact place on github if I'm wrong
> 
> Also moving this issue to `build_tools` repo since it's the place to report issues with build process

That is the problem. bootstrap.sh or bat is calling a script that does not exist.

**Comment by ShockwaveNN** [comment]
Could you point out the exact place in the code in which it is called? I searched, but didn't find any place like this

**Comment by bhlevca** [comment]
I think I am giving up of compiling the source.  Obviously,  the build works in your particular settings and the documentation does not explain well how to reproduce it in a different one. I tried to build directly and with docker none work on my ubuntu 20.04

**Comment by ShockwaveNN** [comment]
I'm sorry to hear, but in this case, I simply do not understand on which line it is failing, it may be nothing to do with the latest version of the compilator on ubuntu 20.04 but maybe for some other reason

And yes, our product is very complicated to compile, so we provide a tested system example in which it should work, but for any other system - it's up to the user to adapt our code to be compatible because we do not have much resources to do that

**Comment by fuzi1996** [comment]
This problem was caused by the failure of initializing the boost sub module during the first compilation, resulting in the incomplete cloning of the boost sub module。
You need to delete the `core/Common/3dParty/boost/boost_1_72_0` folder,and compile again.
I think this issue need to be closed.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by RehArk** [comment]
Hi, I am facing the same issue:
The shell is called in core -> core\Common\3dParty\v8_89\v8\tools\gcmole

**Comment by RehArk** [comment]
This is strange; I have not seen boots in my repository folder.

command ls results:
core        dictionaries                 document-templates    sdkjs        server
build_tools  core-fonts  document-server-integration  onlyoffice.github.io  sdkjs-forms  web-apps

**Comment by RehArk** [comment]
Ok thanks to [fuzi1996](https://github.com/fuzi1996)

After git clone boots manualy, delete the core repository again and rebuild if there is not boots

**Comment by baiyuxiong** [comment]
I fixed with following steps.
1. add time.sleep(360000) after    os.chdir("boost_1_72_0") in scripts/core_common/modules/boost.py
2. sudo docker cp scripts/core_common/modules/boost.py {containerid}:/build_tools/scripts/core_common/modules/boost.py
3. sudo docker start {containerid}
4. sudo docker exec -it cf5b8c0ff2ff /bin/bash
5. cd /core/Common/3dParty/boost/boost_1_72_0
6. git submodule update --recursive
