### ISSUE TITLE
Real time updates of collaborative editing broken since 7.1.0

### ISSUE THREAD

**Issue by JMoVS** [ONLYOFFICE/build_tools#482]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Eversince 7.1 in my nextcloud, real time updates don't work - I only see a red coloured "someone is making changes here" (and yes, I was in quick mode in Onlyoffice word document

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Have the same document open by two users

**What is the expected behavior?**
similar to 7.0.1 just working

**Did this work in previous versions of DocumentServer?**
yes

**DocumentServer version:**
7.1.0

**Operating System:**
DocumentServer Docker base image

**Browser version:**

**Comment by ShockwaveNN** [comment]
Moved this issue to build_tools since it's the base repo for all problems with the compiled version


Judging by errors - I think something wrong with paths for running DocService

https://github.com/ONLYOFFICE/build_tools#running-document-server

Please check that all of them correctly exist and relative paths like `$PWD/../Common/config` point out to correct dirs

**Comment by hrenard** [comment]
Hi !
I get the same error. I thought my custom image was the issue, so I tried the upstream image and still got it.

**Comment by ShockwaveNN** [comment]
@hrenard Since I've never abled to reproduce this error I need exacts steps how to do so, and once again it's probably with some slightly incorrect paths

**Comment by hrenard** [comment]
Okay, I think it has something to do with state in postgres or rabbitmq.

- I first tried to upgrade to `7.1.1.23` with my custom image that was using `node10`. Got the error.
- I then updated my image to use `node14`. Still got the error.
- I then tried the upstream image. Still got the error.
- I recreated postgres and rabbitmq. It worked.
- I re-tried my custom image (with `node14`). Still works.

So, maybe the root cause is `node10` and there is a side effect afterward because of the state.

**Comment by ShockwaveNN** [comment]
> I then tried the upstream image. Still got the error.

What do you mean by `upstream image`. I'm 99% sure that you cannot get this error on our official images, since there is no nodejs bundled

**Comment by hrenard** [comment]
I mean `onlyoffice/documentserver:7.1.1.23`.
My custom build the server, it doesn't bundle node at the runtime.
It's why I think it's a side effect. I compiled bad server with node10 and I guess it borked the db or the queue.

Did you use node10 to compile, @JMoVS?

**Comment by ShockwaveNN** [comment]
> and I guess it borked the db or the queue.

I guess so, I strongly advice to clean DB and queue (not sure if queue can be dirty) between connection to different builds of DocumentServer

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
