### ISSUE TITLE
[fetch & build]: icu

### ISSUE THREAD

**Issue by yuanzuxing** [ONLYOFFICE/build_tools#750]
# Describe your problem:

On Ubuntu 16.04 OS,
Execute the following command:

git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux
./automate.py

...
...
Everything is Ok

Folders: 4
Files: 68
Size:       381880513
Compressed: 92162613
delete warning [file not exist]: ./cef_binary.7z.data
[fetch & build]: icu
svn: E170013: Unable to connect to a repository at URL 'https://github.com/unicode-org/icu/tags/release-58-2/icu4c'
svn: E000104: Error running context: Connection reset by peer
Error (svn): 1
Error (./make.py): 1

The URL 'https://github.com/unicode-org/icu/tags/release-58-2/icu4c' does not exist,Page display 404.

How should I do.

**Comment by igwyd** [comment]
I just rechecked the assembly on Ubuntu 16.04 using the build_tools same as you:
```
git clone https://github.com/ONLYOFFICE/build_tools.git
cd build_tools/tools/linux
./automate.py
```
and didn't get errors.
Could you try again? Update your Ubuntu 16.04 and run build_tools.

**Comment by chongxishen** [comment]
So do I, retry also the same.

OS: ubuntu 22.04

[fetch & build]: icu
svn: E170013: Unable to connect to a repository at URL 'https://github.com/unicode-org/icu/tags/release-58-2/icu4c'
svn: E900002: Subversion support temporarily disabled.

GitHub has temporarily disabled Subversion support as part of a planned brownout
in order to give you advance notice of the upcoming permanent removal of
Subversion support on 2024-01-08.

Please see https://github.blog/2023-01-20-sunsetting-subversion-support/ for details.
Error (svn): 1
Error (./make.py): 1

**Comment by lewis600** [comment]
I can confirm this issue. We had the same issue today.

**Comment by lewis600** [comment]
**1.Manual download**
```
cd /build_tools/scripts/../../core/Common/3dParty/icu
wget https://github.com/unicode-org/icu/releases/download/release-58-3/icu4c-58_3-src.tgz
tar -zxvf icu4c-58_3-src.tgz
```

**2.Modify file**

`vim build_tools/scripts/core_common/modules/icu.py`

**3.Delete two lines of code and save it.**

```
if not base.is_dir("icu"):
    base.cmd("svn", ["export", "https://github.com/unicode-org/icu/tags/release-" + icu_major + "-" + icu_minor + "/icu4c", "./icu", "--non-interactive", "--trust-server-cert"])
```

**Comment by igwyd** [comment]
Agree, I got that error today, too. I created ticket #65795.

**Comment by igwyd** [comment]
It's fixed at https://github.com/ONLYOFFICE/build_tools/commit/0a613734f7ae149ae025a2cf633112d202180339 and already released.

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
