### ISSUE TITLE
after build success in ubuntu ,the index.html not show success

### ISSUE THREAD

**Issue by stereo720712** [ONLYOFFICE/build_tools#98]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
after use build tools build success in ubuntu14.04
i load the page
http://localhost:8000/web-apps/apps/documenteditor/main/index.html
https://imgur.com/a/wsyWOGI
but it not show success

**Operating System:**
ubuntu 14.04 in vm

**Comment by ShockwaveNN** [comment]
Please create all build related issues in https://github.com/ONLYOFFICE/build_tools repo
I've moved it

I think this is correct, since no docs is opened

Please note that DocumentServer builded from source didn't come with any file manager example, no welcome page

You should impelement it yourself (see api.onlyoffice.com) or use our test examples at https://github.com/ONLYOFFICE/document-server-integration

**Comment by ShockwaveNN** [comment]
I'm closing this issue, since no responce and opening url http://localhost:8000/web-apps/apps/documenteditor/main/index.html is not correct way to use DocumentServer
